# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RoomBookingValtech' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RoomBookingValtech
  pod 'Firebase/Core'

  target 'RoomBookingValtechTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'RoomBookingValtech-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RoomBookingValtech-tvOS

  target 'RoomBookingValtech-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
